# Golden Path configuration for segmentation platform
project_name: "segmentation_experiment"
task: "segmentation"

# SDD v4.0 Golden Path - explicit settings
use_fallbacks: false  # NEVER true in production
validation_mode: "strict"  # Explicit STRICT per SDD v4.0 Appendix A.1

# Dataset configuration
dataset:
  name: "example"
  images_dir: "./data/images"
  masks_dir: "./data/masks"
  image_suffix: ".png"
  mask_suffix: "_mask.png"
  split:
    type: "random"
    val_ratio: 0.2
    seed: 42

# Model configuration
model:
  architecture: "Unet"
  encoder: "resnet34"
  encoder_weights: "imagenet"
  in_channels: 3
  classes: 1

# Training configuration
training:
  epochs: 50
  batch_size: 8
  learning_rate: 1e-4
  optimizer: "adamw"
  weight_decay: 1e-4
  scheduler:
    type: "cosine"
    min_lr: 1e-6
  loss:
    type: "dice"
    params:
      smooth: 1.0
  metrics: ["dice", "iou"]
  accumulate_grad_batches: 1

# Resource management OFF by default
resources:
  auto_tune: false  # Must explicitly enable
  log_effective_settings: true  # Always log what ran

# Augmentations
augmentations:
  train:
    - name: "RandomRotate90"
      params:
        p: 0.5
    - name: "HorizontalFlip"
      params:
        p: 0.5
    - name: "RandomBrightnessContrast"
      params:
        brightness_limit: 0.2
        contrast_limit: 0.2
        p: 0.5
  val: []

# Output configuration
output:
  dir: "./runs"
  save_overlays: true
  save_predictions: true
  checkpoint:
    monitor: "val_loss"
    mode: "min"
    save_best_only: true

# Simple visualization defaults
visualization:
  mode: "simple"  # Not "detailed" by default
  overlay_alpha: 0.3
  overlay_colormap: "viridis"

# Compute settings
compute:
  accelerator: "auto"
  devices: 1
  precision: 32
  deterministic: true
  seed: 42

# Logging
logging:
  level: "INFO"
  save_tensorboard: false